In [1]:
import pandas as pd

# Load the dataset
try:
    df = pd.read_csv('../data_raw/us-shein-sports_and_outdoors-3853.csv')
except ValueError:
    print("Unable to load the dataset into notebook")
except FileNotFoundError:
    print("Unable to find the file in that path")

In [2]:
# Show the head of dataset
df.head()

,color-count,blackfridaybelts-bg src,blackfridaybelts-content,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,5.0,https://img.ltwebstatic.com/images3_ccc/2023/1...,Save $5.24,"3pcs/Set Women Seamless Yoga Shorts, High Wais...",https://us.shein.com/3pcs-Set-Women-Seamless-Y...,#9 Best Sellers,in Women Sports Shorts,$7.85,-40%,NaN,NaN
1,NaN,NaN,NaN,"1 Pc Battery Operated Mini Portable Fan, Light...",https://us.shein.com/1-Pc-Battery-Operated-Min...,#5 Best Sellers,in Camping & Hiking,$1.02,-67%,NaN,NaN
2,8.0,NaN,NaN,"Sports Shoes, Street Sports Shoes, Men's And W...",https://us.shein.com/Sports-Shoes-Street-Sport...,#1 Best Seller,In Black and White Men Sneakers,$88.70,-24%,NaN,NaN
3,13.0,https://img.ltwebstatic.com/images3_ccc/2023/1...,Save $6.53,SHEIN Yoga Basic Seamless High Stretch Sports Set,https://us.shein.com/SHEIN-Yoga-Basic-Seamless...,NaN,NaN,$5.96,-52%,3.1k+ sold recently,NaN
4,NaN,https://img.ltwebstatic.com/images3_ccc/2023/1...,Save $2.55,Tennis Basic Pleated Detail Sports Skort With ...,https://us.shein.com/Tennis-Basic-Pleated-Deta...,NaN,NaN,$7.64,-25%,8.3k+ sold recently,NaN

In [3]:
# Show the sample from the dataset
df.sample(5)

,color-count,blackfridaybelts-bg src,blackfridaybelts-content,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
102,NaN,NaN,NaN,NaN,NaN,#1 Best Sellers,in Athletic Socks,$1.20,NaN,NaN,"1/5/10 Pair Essential Ankle Socks, Soft & Ligh..."
1121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,$5.79,-6%,80+ sold recently,"Women's Butt Lifter Underwear, Natural Butt Li..."
3426,NaN,https://img.ltwebstatic.com/images3_ccc/2023/1...,Save $8.57,NaN,NaN,#5 Best Sellers,in Wind-Proof Men Outdoor Apparel,$25.73,-25%,NaN,Men's Vintage-Style Distressed Leather Jacket ...
628,4.0,https://img.ltwebstatic.com/images3_ccc/2023/1...,Save $7.22,NaN,NaN,NaN,NaN,$21.67,-25%,600+ sold recently,SHEIN Sport Gameset Women Solid Color Shorts S...
3020,NaN,NaN,NaN,NaN,NaN,#6 Best Sellers,in Fishing Accessories,$3.26,-54%,NaN,"2pcs/set Car Fishing Rod Mount Holder, With Ba..."

In [4]:
# Check the shape of the dataset
df.shape

(3852, 11)

In [5]:
# Show the dataset columns
df.columns

Index(['color-count', 'blackfridaybelts-bg src', 'blackfridaybelts-content',
       'goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='object')

In [6]:
# Check missing values
df.isnull().sum()

color-count                    2637
blackfridaybelts-bg src        2281
blackfridaybelts-content       2281
goods-title-link--jump         3813
goods-title-link--jump href    3813
rank-title                     2666
rank-sub                       2666
price                             0
discount                        627
selling_proposition            1359
goods-title-link                 39
dtype: int64

In [7]:
# Check duplicates
df.duplicated().sum()

np.int64(117)

In [8]:
# Drop duplicates
df.drop_duplicates(inplace=True)

In [9]:
# Apply the cleaning data function
import utils as ut

df_clean = ut.clean_dataset(df)

In [10]:
# Show the cleaned dataset
df_clean.head()

,price,discount,selling_proposition,product_title,rank_number,rank_type,rank_category,is_ranked
0,7.85,40,0,"3pcs/Set Women Seamless Yoga Shorts, High Wais...",9.0,Best Sellers,Women Sports Shorts,1
1,1.02,67,0,"1 Pc Battery Operated Mini Portable Fan, Light...",5.0,Best Sellers,Camping & Hiking,1
2,88.70,24,0,"Sports Shoes, Street Sports Shoes, Men's And W...",1.0,Best Seller,In Black and White Men Sneakers,1
3,5.96,52,3100,SHEIN Yoga Basic Seamless High Stretch Sports Set,NaN,NaN,NaN,0
4,7.64,25,8300,Tennis Basic Pleated Detail Sports Skort With ...,NaN,NaN,NaN,0

In [11]:
# Show the sample from the cleaned dataset
df_clean.sample(5)

,price,discount,selling_proposition,product_title,rank_number,rank_type,rank_category,is_ranked
2224,10.15,20,0,Shapewear For Women Tummy Control Fajas Post S...,5.0,Best Sellers,Women Shapewear Bodysuits,1
903,3.30,13,400,2/3/4/5pcs Portable Mini Transparent Zipper St...,NaN,NaN,NaN,0
996,1.60,0,1500,"1/3/5 Pair Lifting Silicone Nipple Covers, Str...",NaN,NaN,NaN,0
3828,14.00,25,0,Men Ribbed Breathable Running Shoes,NaN,NaN,NaN,0
2460,7.17,30,100,"1pc, 20oz Skinny Sublimation Tumbler, Stainles...",NaN,NaN,NaN,0

In [12]:
# Save the cleaned dataset
df_clean.to_csv('../data_cleaned/cleaned_shein_sports_and_outdoors.csv', index=False)